#! /usr/bin/env python

from __future__ import print_function
import sys
import getopt
from elfesteem import ELF


def usage():
    print("Usage: elfcli [-i inputfile]", file=sys.stderr)
    raise SystemExit

def main(*args):
    INPUT=sys.stdin
    try:
        opts = getopt.getopt(args,"hi:")
        for opt,optarg in opts[0]:
            if opt == "-h":
                usage()
            if opt == "-i":
                INPUT = open(optarg)
    except getopt.GetoptError as e:
        print("ERROR: %s" % e, file=sys.stderr)
        raise SystemExit
    

if __name__ == "__main__":
    main(*sys.argv[1:])
